### ISSUE TITLE
s3 backed container doesn't see modules/providers after restart

### ISSUE THREAD

**Issue by AndriiOmelianenko** [outsideris/citizen#101]
I'm using citizen in kubernetes, with an s3 bucket enabled backend.
In general, it works well; files are being stored in s3.

However, the citizen doesn't see the providers/modules stored in s3 after the pod restarts. It can publish new ones, but previous ones are not visible anymore.

As I understand - it's because by default it uses local `nedb` file as database, which is being erased after pod restart.
Anyway, it's just a bit confusing, that even if you configured storage backend with s3, after restart it breaks basically. Could it be fixed maybe - if storage backend is configured - then nedb file is also stored there?

**Comment by outsideris** [comment]
Sorry for your inconvinient.
The `nedb` is not supported remote features and the project is deprecated. So, I will change the nedb to sqlite. 

I think db and storage are different. Not everyone uses kubernetes. And erasing after pot restart is not citizen's responsible I think. If users use local filesystem, they should handle volume for pod. 

Sorry, I will close this issue because I dropped the `nedb`.
